DROP TABLE LOGER; --  CASCADE CONSTRAINTS
DROP TABLE RESEAUSOCIAL; --  CASCADE CONSTRAINTS
DROP TABLE RESERVATION; --  CASCADE CONSTRAINTS
DROP TABLE BILLET; --  CASCADE CONSTRAINTS         
DROP TABLE TYPEBILLET; --  CASCADE CONSTRAINTS     
DROP TABLE ACTIVITEANNEXE; --  CASCADE CONSTRAINTS 
DROP TABLE FAVORIS; --  CASCADE CONSTRAINTS        
DROP TABLE IMAGER_GROUPE;
DROP TABLE VIDEO_GROUPE;
DROP TABLE CONCERT; --  CASCADE CONSTRAINTS     
DROP TABLE ARTISTE; --  CASCADE CONSTRAINTS        
DROP TABLE GROUPE; --  CASCADE CONSTRAINTS      
DROP TABLE JOUER; --  CASCADE CONSTRAINTS          
DROP TABLE UTILISATEUR; --  CASCADE CONSTRAINTS    
DROP TABLE ROLEUTI; --  CASCADE CONSTRAINTS     
DROP TABLE HEBERGEMENT; --  CASCADE CONSTRAINTS 
DROP TABLE PHOTO; --  CASCADE CONSTRAINTS         
DROP TABLE VIDEO; --  CASCADE CONSTRAINTS
DROP TABLE STYLEMUSICAL; --  CASCADE CONSTRAINTS
DROP TABLE INSTRUMENT; --  CASCADE CONSTRAINTS  
DROP TABLE LIEU; --  CASCADE CONSTRAINTS        
DROP TABLE FESTIVAL; --  CASCADE CONSTRAINTS    